name = "Halton"
uuid = "93b8ac21-ba3c-4dcb-9f40-eea070e3f6a3"
authors = ["Nick Frazier <https://github.com/npfrazier>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
